name: env_cwl_wrapper
channels:
  - terradue
  - conda-forge
dependencies:
  - jinja2
  - pyyaml
  - click
  - click2cwl>=0.3.3
  - black
  - pre-commit
  - isort
  - flake8
  - autoflake
  - pylint
  - nose2
  - cwltool
  - pip:
    - loguru
